# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
services:
  # For dependencies, expose ports locally for dev
  mongo1:
    ports:
      - '27017:27017'
    volumes:
      - './data/mongo:/data/db'

  redis:
    ports:
      - '6379:6379'

  elasticsearch:
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - './data/elasticsearch:/usr/share/elasticsearch/data'
      - './data/backups/elasticsearch:/data/backups/elasticsearch'
    environment:
      - 'discovery.type=single-node'
      - 'cluster.routing.allocation.disk.watermark.enable_for_single_data_node=true'
      - 'cluster.routing.allocation.disk.threshold_enabled=false'
      - path.repo=/data/backups/elasticsearch
      - 'ES_JAVA_OPTS=-Xms1024m -Xmx1024m'
      - xpack.security.enabled=false # elasticsearch >8.x defaults to true
      # - http.port=9200
      # - http.cors.allow-origin=http://localhost:1358,http://127.0.0.1:1358
      # - http.cors.enabled=true
      # - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      # - http.cors.allow-credentials=true

  # elasticsearch browser.  Uncomment during development, along with the environment variables for elastic above, to browse Elastic via a GUI at http://localhost:1358/
  #dejavu:
  #  image: appbaseio/dejavu:3.2.3
  #  container_name: dejavu
  #  ports:
  #    - '1358:1358'
  #  links:
  #    - elasticsearch
  minio:
    ports:
      - '3535:3535'
      - '3536:3536'
    volumes:
      - './data/minio:/data'
    command: server --address ":3535" --console-address ":3536" /data

  influxdb:
    ports:
      - '8086:8086'
    volumes:
      - './data/influxdb:/var/lib/influxdb'
      - './data/backups/influxdb:/data/backups/influxdb'
      - './infrastructure/influxdb.conf:/etc/influxdb/influxdb.conf'
      # Expose dev secrets as a plain volume - these will use docker secrets in staging and prod
  hearth:
    environment:
      - logger__level=warn
    volumes:
      - '.secrets/public-key.pem:/secrets/public-key.pem'
      - './infrastructure/hearth-plugins/checkDuplicateTask.js:/src/hearth/lib/plugins/checkDuplicateTask.js'
      - './infrastructure/hearth-queryparam-extensions.json:/src/hearth/config/queryparam-extensions.json'
    ports:
      - '3447:3447'

  family-tree:
    build:
      context: ../family-tree
      dockerfile: ./docker/Dockerfile
    env_file:
      - ../family-tree/.env
    depends_on:
      - postgres
    volumes:
      - ../family-tree/src:/app/src
      - ../family-tree/public:/app/public
      - ../family-tree/.env:/app/.env
      - family_tree_nextjs_cache:/app/.next
    ports:
      - '3888:3888'

  postgres:
    image: postgres:15
    container_name: person_registry_pg
    restart: always
    environment:
      POSTGRES_DB: person_registry
      POSTGRES_USER: registry_user
      POSTGRES_PASSWORD: registry_pass
    ports:
      - '5432:5432'
    volumes:
      - family_tree_pgdata:/var/lib/postgresql/data

  opensearch:
    build:
      context: ../opensearch
      dockerfile: Dockerfile.opensearch
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=WelcomeDemo1.23@
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch_data:/usr/share/opensearch/data
      - ../opensearch/init:/init
    ports:
      - '19200:9200'
      - '19600:9600'

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3.0.0
    container_name: opensearch-dashboards
    environment:
      OPENSEARCH_HOSTS: 'http://opensearch:9200'
      # OPENSEARCH_USERNAME: 'admin'
      # OPENSEARCH_PASSWORD: WelcomeDemo1.23@
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: 'true'
    depends_on:
      - opensearch
    ports:
      - '5601:5601'

volumes:
  family_tree_pgdata:
  family_tree_node_modules:
  family_tree_nextjs_cache:
  opensearch_data:
