#!/bin/bash

# Enhanced log parsing utility for OpenCRVS ATG development
# Extracts per-service logs from lerna's combined output for easier AI debugging
# This script parses the all-services.log file and creates individual service log files

set -euo pipefail

# Function to display usage
print_help() {
    echo "Usage: $0 [LOG_DIRECTORY]"
    echo ""
    echo "Parse OpenCRVS service logs from lerna output into individual service files"
    echo ""
    echo "Arguments:"
    echo "  LOG_DIRECTORY    Path to log directory (default: latest logs/atg-* directory)"
    echo ""
    echo "Options:"
    echo "  --help, -h       Show this help message"
    echo ""
    echo "Examples:"
    echo "  $0                                    # Parse latest ATG logs"
    echo "  $0 logs/atg-20250921-143022          # Parse specific log directory"
    echo ""
    echo "Output:"
    echo "  Creates individual [service].log files in the log directory"
    echo "  Updates service-summary.log with service status and error counts"
}

# Parse command line arguments
LOG_DIR=""
while [[ $# -gt 0 ]]; do
    case $1 in
        --help|-h)
            print_help
            exit 0
            ;;
        *)
            if [ -z "$LOG_DIR" ]; then
                LOG_DIR="$1"
            else
                echo "Error: Unknown argument: $1"
                print_help
                exit 1
            fi
            shift
            ;;
    esac
done

# Find the latest log directory if not specified
if [ -z "$LOG_DIR" ]; then
    SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
    ROOT_DIR=$(cd "$SCRIPT_DIR/.." && pwd)

    # Find the latest ATG log directory
    LOG_DIR=$(find "$ROOT_DIR/logs" -name "atg-*" -type d 2>/dev/null | sort | tail -1)

    if [ -z "$LOG_DIR" ]; then
        echo "Error: No ATG log directories found in logs/"
        echo "Run 'yarn dev-atg' first to generate logs"
        exit 1
    fi

    echo "Using latest log directory: $LOG_DIR"
fi

# Validate log directory and input file
if [ ! -d "$LOG_DIR" ]; then
    echo "Error: Log directory not found: $LOG_DIR"
    exit 1
fi

ALL_SERVICES_LOG="$LOG_DIR/all-services.log"
if [ ! -f "$ALL_SERVICES_LOG" ]; then
    echo "Error: all-services.log not found in: $LOG_DIR"
    echo "Make sure to run the enhanced dev-atg.sh script first"
    exit 1
fi

echo "Parsing service logs from: $ALL_SERVICES_LOG"

# Initialize service summary
SUMMARY_FILE="$LOG_DIR/service-summary.log"
echo "# OpenCRVS Service Log Summary - $(date -Iseconds)" > "$SUMMARY_FILE"
echo "# Generated by parse-service-logs.sh" >> "$SUMMARY_FILE"
echo "" >> "$SUMMARY_FILE"

# Parse the lerna output and extract service-specific logs
# Lerna typically outputs lines in format: [service-name] log message
echo "Extracting per-service logs..."

# Track discovered services
declare -A SERVICES_FOUND
declare -A ERROR_COUNTS
declare -A LINE_COUNTS

# Process the main log file
while IFS= read -r line; do
    # Extract service name from lerna format: [service-name] message
    if [[ $line =~ ^\[([^\]]+)\]\ (.*)$ ]]; then
        service="${BASH_REMATCH[1]}"
        message="${BASH_REMATCH[2]}"

        # Clean service name (remove colors, special chars)
        clean_service=$(echo "$service" | sed 's/\x1b\[[0-9;]*m//g' | tr -d ' ')

        # Skip empty service names
        if [ -n "$clean_service" ]; then
            SERVICES_FOUND["$clean_service"]=1

            # Write to service-specific log file
            SERVICE_LOG="$LOG_DIR/${clean_service}.log"
            echo "$line" >> "$SERVICE_LOG"

            # Count lines and errors
            LINE_COUNTS["$clean_service"]=$((${LINE_COUNTS["$clean_service"]:-0} + 1))

            # Count errors (case-insensitive)
            if echo "$message" | grep -qi "error\|exception\|failed\|fatal"; then
                ERROR_COUNTS["$clean_service"]=$((${ERROR_COUNTS["$clean_service"]:-0} + 1))
            fi
        fi
    else
        # Lines without service prefix go to general.log
        echo "$line" >> "$LOG_DIR/general.log"
    fi
done < "$ALL_SERVICES_LOG"

# Generate service summary
echo "Services discovered: ${#SERVICES_FOUND[@]}"
echo "SERVICE_COUNT=${#SERVICES_FOUND[@]}" >> "$SUMMARY_FILE"
echo "" >> "$SUMMARY_FILE"

if [ ${#SERVICES_FOUND[@]} -gt 0 ]; then
    echo "SERVICE_LOGS:" >> "$SUMMARY_FILE"
    for service in "${!SERVICES_FOUND[@]}"; do
        line_count=${LINE_COUNTS["$service"]:-0}
        error_count=${ERROR_COUNTS["$service"]:-0}

        echo "  $service.log: $line_count lines, $error_count errors" >> "$SUMMARY_FILE"
        echo "    ✓ $service: $line_count lines, $error_count errors"

        # Create AI-friendly quick status
        if [ "$error_count" -gt 0 ]; then
            echo "STATUS_${service}=ERROR_COUNT_${error_count}" >> "$SUMMARY_FILE"
        else
            echo "STATUS_${service}=OK" >> "$SUMMARY_FILE"
        fi
    done
else
    echo "WARNING: No services found in lerna output format" >> "$SUMMARY_FILE"
    echo "This might indicate the services are not running or using a different log format" >> "$SUMMARY_FILE"
fi

echo "" >> "$SUMMARY_FILE"
echo "# AI Debugging Commands:" >> "$SUMMARY_FILE"
echo "# View errors across all services: grep -i error $LOG_DIR/*.log" >> "$SUMMARY_FILE"
echo "# View specific service: cat $LOG_DIR/[service-name].log" >> "$SUMMARY_FILE"
echo "# View service startup issues: grep -i 'start\|init\|ready' $LOG_DIR/*.log" >> "$SUMMARY_FILE"

echo ""
echo "✅ Log parsing complete!"
echo "📁 Individual service logs created in: $LOG_DIR"
echo "📋 Service summary: $SUMMARY_FILE"
echo ""
echo "AI-friendly commands:"
echo "  cat $SUMMARY_FILE                     # View service overview"
echo "  grep -i error $LOG_DIR/*.log          # Find all errors"
echo "  ls $LOG_DIR/*.log                     # List all service logs"