apiVersion: v1
kind: Service
metadata:
  labels:
    app: client
  name: client
spec:
  ports:
    - port: 3000
      targetPort: 80
  selector:
    app: client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client
  name: client
spec:
  replicas: {{ .Values.client.replicas }}
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - image: "opencrvs/ocrvs-client:{{ .Values.image.tag }}"
          name: client
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
