apiVersion: v1
kind: Service
metadata:
  labels:
    app: events
  name: events
spec:
  ports:
    - port: 5555
      targetPort: 5555
  selector:
    app: events
  type: LoadBalancer
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: events-route
spec:
  entryPoints:
    - websecure
  routes:
  - match: 'Host(`events.{{ .Values.hostname }}`)'
    kind: Rule
    services:
    - name: events
      namespace: opencrvs-services-dev
      port: 5555
    middlewares:
      - name: sts-and-basic-response-headers
  tls:
    certResolver: myresolver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: events
  name: events
spec:
  replicas: {{ .Values.events.replicas }}
  selector:
    matchLabels:
      app: events
  template:
    metadata:
      labels:
        app: events
    spec:
      containers:
        - name: events
          image: "opencrvs/ocrvs-events:{{ .Values.image.tag }}"
          env:
            - name: ES_HOST
              value: elasticsearch.opencrvs-deps-dev.svc.cluster.local:9200
            - name: MONGO_URL
              value: mongodb://mongodb-0.mongodb.opencrvs-deps-dev.svc.cluster.local/events
          ports:
            - containerPort: 5555
              protocol: TCP
      restartPolicy: Always
