apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway
  name: gateway
spec:
  ports:
    - port: 7070
      targetPort: 7070
  selector:
    app: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway
  name: gateway
spec:
  replicas: {{ .Values.gateway.replicas }}
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: "opencrvs/ocrvs-gateway:{{ .Values.image.tag }}"
          env:
            - name: APPLICATION_CONFIG_URL
              value: http://config:2021/
            - name: AUTH_URL
              value: http://auth:4040
            - name: CERT_PUBLIC_KEY_PATH
              value: /secrets/public-key.pem
            - name: CHECK_INVALID_TOKEN
              value: "true"
            - name: CONFIG_SMS_CODE_EXPIRY_SECONDS
              value: "600"
            - name: CONFIG_TOKEN_EXPIRY_SECONDS
              value: "604800"
            - name: COUNTRY_CONFIG_URL
              value: http://countryconfig:3040
            - name: DOCUMENTS_URL
              value: http://documents:9050
            - name: FHIR_URL
              value: http://hearth:3447/fhir
            - name: METRICS_URL
              value: http://metrics:1050
            - name: MINIO_BUCKET
              value: ocrvs
            - name: NODE_ENV
              value: development
            - name: NOTIFICATION_URL
              value: http://notification:2020/
            - name: REDIS_HOST
              value: redis
            - name: SEARCH_URL
              value: http://search:9090/
            - name: USER_MANAGEMENT_URL
              value: http://user-mgnt:3030/
            - name: WEBHOOKS_URL
              value: http://webhooks:2525/
            - name: WORKFLOW_URL
              value: http://workflow:5050/
          ports:
            - containerPort: 7070
              protocol: TCP
          volumeMounts:
            - mountPath: /secrets/public-key.pem
              name: public-key
              subPath: public-key.pem
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: public-key.pem
                path: public-key.pem
            name: public-key
          name: public-key