apiVersion: v1
kind: Service
metadata:
  labels:
    app: metrics
  name: metrics
spec:
  ports:
    - port: 1050
      targetPort: 1050
  selector:
    app: metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metrics
  name: metrics
spec:
  replicas:  {{ .Values.metrics.replicas }}
  selector:
    matchLabels:
      app: metrics
  template:
    metadata:
      labels:
        app: metrics
    spec:
      containers:
        - image: "opencrvs/ocrvs-metrics:{{ .Values.image.tag }}"
          name: metrics
          env:
            - name: CERT_PUBLIC_KEY_PATH
              value: /secrets/public-key.pem
            - name: CONFIG_API_URL
              value: http://config:2021
            - name: COUNTRY_CONFIG_URL
              value: http://countryconfig:3040/
            - name: DASHBOARD_MONGO_URL
              value: mongodb://mongo1/performance
            - name: DOCUMENTS_URL
              value: http://documents:9050
            - name: FHIR_URL
              value: http://hearth:3447/fhir
            - name: HEARTH_MONGO_URL
              value: mongodb://mongo1/hearth-dev
            - name: INFLUX_DB
              value: ocrvs
            - name: INFLUX_HOST
              value: influxdb
            - name: INFLUX_PORT
              value: "8086"
            - name: MONGO_URL
              value: mongodb://mongo1/metrics
            - name: SEARCH_URL
              value: http://search:9090/
            - name: USER_MANAGEMENT_URL
              value: http://user-mgnt:3030

          ports:
            - containerPort: 1050
              protocol: TCP
          volumeMounts:
            - mountPath: /secrets/public-key.pem
              name: public-key
              subPath: public-key.pem
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: public-key.pem
                path: public-key.pem
            name: public-key
          name: public-key